### ISSUE TITLE
Slow deeplexicon - Ways to improve

### ISSUE THREAD

**Issue by ADelgadoT** [biocorecrg/master_of_pores#36]
Hi everyone, 

NanoPreprocess, specifically deeplexicon, has been running for more than three days to demultiplex a one million reads sample. It is running, it does not crush but it is not efficient. We should try to make it more efficient. At the moment, if I'm not mistaken, we are analysing one multi fast5 per time (in parallel). Any ideas?

**Comment by lucacozzuto** [comment]
Are you using the cluster?

**Comment by ADelgadoT** [comment]
No, she is running it in MinION as she had to basecall using GPU.

**Comment by lucacozzuto** [comment]
I think this is the problem. I suggest you to do the basecalling with GPU and then demultiplexing on the cluster, so you can use up to 100 nodes per time.

**Comment by lucacozzuto** [comment]
when we will have a GPU version of deeplexicon we can do everything on a single computer.

**Comment by enovoa** [comment]
This points to the urge of being able to run MoP on base-called fastq.
The most efficient strategy would be to skip MoP for basecalling (i.e. do it ourselves), and then only launch MoP once we have fastq.

**Comment by lucacozzuto** [comment]
The demultiplexing is done on fast5 files. So also skipping the basecalling and starting from fastq won't speed up the demultiplexing. You can do the basecalling as you prefer and then use basecalled fast5 for the pipeline in the cluster with 100 CPUs

**Comment by enovoa** [comment]
Yes, we can use basecalled fast5 in the cluster with 100CPUs. The only thing is that we typically do not store basecalled fast5, it is an unnecessary use of space. Fast5 + FASTq contain the same information as basecalled fast5. So storing Fast5, fastq and basecalled fast5 is redundancy. 

Hence or need to be able to launch MoP using FASTQ (and raw FAST5), but not base-called fast5. Also because we would have to rebasecall absolutely everything that we have sequenced so far (we only store basecalled fastq and raw fast5 as I mentioned). 

Thanks!

**Comment by lucacozzuto** [comment]
Well this is way more complex... the storage of basecalled fast5 is not necessary once the pipeline is finished you simply remove it. We will discuss in few minutes.
