### ISSUE TITLE
cDNA pipeline with guppy or guppy+porechop

### ISSUE THREAD

**Issue by enovoa** [biocorecrg/master_of_pores#37]

**Comment by ADelgadoT** [comment]
Hi, 

Instead of including porechop in MoP, which is deprecated, we should include readucks (link: https://github.com/artic-network/readucks/). 

I haven't test the tool, but according to their documentation, we should implement this command: 
readucks -i /path/to/fastq/files -o /output/directory --annotate_files --native_barcodes --threshold 50

If only using barcodes at one end of the read: 
readucks -i /path/to/fastq/files -o /output/directory --annotate_files --native_barcodes --threshold 50 --single

**IMPORTANT:** the option --native_barcodes implies that the software will only try to match the 24 native nanopore barcodes, if the barcodes aren't those, we should change the parameter. I'll deep more into the topic.

**Comment by ADelgadoT** [comment]
Commands tested, they work fine. With the current sample, readucks can classify around 11% of the reads which are unclassified bu guppy demultiplexing.
